package org.manis.erp.entities;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "universityDetails")
public class UniversityDetails {
    @Id
    private ObjectId id;

    private String campusName;
    private String programType;
    private String programName;
    private int semester;



    // Getters and setters are generated by Lombok's @Data annotation
}
